version: "3.8"

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network

  frontend:
    build: ./frontend/app
    ports:
      - "3000:3000"
    networks:
      - app-network
      - keycloak-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./API1
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - keycloak-network
      - app-network
    depends_on:
      - keycloak

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: superSecret
      MYSQL_DATABASE: posts_db
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

volumes:
  keycloak-db-data:
  db-data:

networks:
  keycloak-network:
  app-network:
